# Generated by Django 4.0.4 on 2022-05-06 14:12

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_card_number_alter_payment_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
    ]
