# Generated by Django 4.0.4 on 2022-05-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sequrity',
        ),
    ]
