# Generated by Django 4.0.4 on 2022-05-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='orderdetails',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
    ]
